### ISSUE TITLE
how to change swd pins 

### ISSUE THREAD

**Issue by hmz06967** [martijnvwezel/pico-probe-programmer#2]
picoprobe's swd 2 and 3 io pins, but I want these pins 6 and 7, is it possible? Also, when compiling it myself, if the utf size is 76kb, where am I going wrong with 50kb?
![wrong](https://user-images.githubusercontent.com/10728502/182019860-67e6e1eb-5c3d-45a3-aeb4-4bfa83750810.PNG)

**Comment by martijnvwezel** [comment]
Should be possible, don't see a reason why not. If you changed them in the pin header, you compile it and you can drag the `.uf2` file to the storage of the pico. You are not doing anything wrong it's the way `.uf2` works. It contained more information etc.

**Comment by hmz06967** [comment]
Thank you, please can you changed pins 2 and 3 to other pins and after building your pc make send me uf2? Do you can a for me?

**Comment by martijnvwezel** [comment]
I am currently not close to my computer: the only change you need to do is the following :
![image](https://user-images.githubusercontent.com/4363788/182604841-e9cde3c7-7572-46f3-a8cc-bff010f402e3.png)
Changing the 2 to 6. The rest of the module is a PIO module which means the next pin number should be in line with the one given so 2 where `swdio pin = [swclk+1]`

**Comment by hmz06967** [comment]
Thank you

**Comment by martijnvwezel** [comment]
And you have to change the 
![image](https://user-images.githubusercontent.com/4363788/182856854-4cacb108-7b99-4d0c-8c37-4315f624af5d.png)

 to some pin you like
